### ISSUE TITLE
missing filepath?

### ISSUE THREAD

**Issue by ExileFox** [NickToony/gd-retroterrain#1]
>   No loader found for resource: res://Main.cs (expected type: Script)
>   No loader found for resource: res://Terrain.cs (expected type: Script)
>   No loader found for resource: res://WaterPlane.cs (expected type: Script)
>   No loader found for resource: res://FPSCamera.cs (expected type: Script)
>   No loader found for resource: res://RTSCamera.cs (expected type: Script)

**Comment by ExileFox** [comment]
oh. Godot doesn't tell you which edition a project is for.

**Comment by NickToony** [comment]
If anyone has this issue again: this is happening because the C# project is being opened in a version of Godot without .net.

This is no longer an issue since the project is using GDScript as of v1.1.
